// Generated by AutoModule - DO NOT edit - it'll be overridden
import org.gradle.api.artifacts.Dependency
import org.gradle.api.artifacts.dsl.DependencyHandler
import org.gradle.kotlin.dsl.project

val DependencyHandler.projects: Projects
  get() = Projects(this)

class Projects(
  dh: DependencyHandler
) {
  val resource: Dependency = dh.project(":resource")
}
