// Generated by AutoModule - DO NOT edit - it'll be overridden
import org.gradle.api.artifacts.Dependency
import org.gradle.api.artifacts.dsl.DependencyHandler
import org.gradle.kotlin.dsl.project

val DependencyHandler.projects: Projects
  get() = Projects(this)

class Projects(
  dh: DependencyHandler
) {
  val demo: Demo = Demo(dh)

  val resource: Dependency = dh.project(":resource")

  class Demo(
    dh: DependencyHandler,
    dependency: Dependency = dh.project(":demo")
  ) : Dependency by dependency {
    val app: Dependency = dh.project(":demo:app")

    val backend: Dependency = dh.project(":demo:backend")
  }
}
