name: Build

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: gradle build --build-cache
      - name: Tests
        run: gradle test
