on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: gradle build --build-cache

      - name: Tests
        run: gradle allTest

      - name: Generate tests report
        run: gradle jacocoTestReport

      - uses: codecov/codecov-action@v1
        with:
          file: resource/build/reports/jacoco/report.xml

      - name: Maven publish
        env:
          ossUser: ${{ secrets.ossUser }}
          ossPass: ${{ secrets.ossPass }}
          gpgKeyName: ${{ secrets.gpgKeyName }}
          gpgPassphrase: ${{ secrets.gpgPassphrase }}
        run: gradle publishAllPublicationsToMavenRepository -Psigning.gnupg.keyName=${{ secrets.gpgKeyName }} -Dsigning.gnupg.passphrase=${{ secrets.gpgPassphrase }}
