name: Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build --build-cache

      - name: Tests
        run: ./gradlew allTest

      - name: Generate tests report
        run: ./gradlew jacocoTestReport

      - uses: codecov/codecov-action@v1
        with:
          file: resource/build/reports/jacoco/report.xml

      - name: GPG setup
        env:
          gpgKey: ${{ secrets.gpgKey }}
        run: |
          cat <(echo -e "${{ secrets.gpgKey }}") | gpg --batch --import

      - name: Maven publish
        env:
          ossUser: ${{ secrets.ossUser }}
          ossToken: ${{ secrets.ossToken }}
          gpgKeyName: ${{ secrets.gpgKeyName }}
          gpgPassphrase: ${{ secrets.gpgPassphrase }}
        run: ./gradlew publishToSonatype -PisLibRelease=true -Psigning.gnupg.keyName=${{ secrets.gpgKeyName }} -Psigning.gnupg.passphrase=${{ secrets.gpgPassphrase }}

      - name: Close Maven repository
        env:
          ossUser: ${{ secrets.ossUser }}
          ossToken: ${{ secrets.ossToken }}
        run: ./gradlew closeRepository

      - name: Publish docs
        env:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew docs:orchidDeploy
